### ISSUE TITLE
Use Winston for logging

### ISSUE THREAD

**Issue by bw-allardvanhelbergen** [bw-allardvanhelbergen/go#12]
- [x] Add winston to the app
- [x] Replace all console logging thingies for winston calls
- [x] Add the logging values to the config files
- [x] Figure out if util.inspect is necessary
- [x] Add logging points for every significant event
- [x] Add a check that deals with the log dir not being there

**Comment by bw-allardvanhelbergen** [comment]
#62 Added basic logging.

**Comment by bw-allardvanhelbergen** [comment]
Need to add sth that creates the logs dir, if it doesn't exist yet.

**Comment by larister** [comment]
ah yeah, good shout soz

**Comment by larister** [comment]
Node purists will puke but as this happens at app startup, I'd suggest using `fs.statSync` (for detection) and `fs.mkdirSync` (for making the dir) to avoid having to handle async headaches.

**Comment by bw-allardvanhelbergen** [comment]
Learned that, due to potential race conditions, detection is superfluous activity. The approach is to create the directory regardless and handle the error if it already exists.

**Comment by larister** [comment]
Ah yes, good plan.

**Comment by bw-allardvanhelbergen** [comment]
Done
